export type Country = {
  name: string
  iso: string
  dial: string
}

export const countries: Country[] = [
  { name: "Afghanistan", iso: "AF", dial: "93" },
  { name: "Albania", iso: "AL", dial: "355" },
  { name: "Algeria", iso: "DZ", dial: "213" },
  { name: "Argentina", iso: "AR", dial: "54" },
  { name: "Armenia", iso: "AM", dial: "374" },
  { name: "Australia", iso: "AU", dial: "61" },
  { name: "Austria", iso: "AT", dial: "43" },
  { name: "Azerbaijan", iso: "AZ", dial: "994" },
  { name: "Bahrain", iso: "BH", dial: "973" },
  { name: "Bangladesh", iso: "BD", dial: "880" },
  { name: "Belarus", iso: "BY", dial: "375" },
  { name: "Belgium", iso: "BE", dial: "32" },
  { name: "Brazil", iso: "BR", dial: "55" },
  { name: "Bulgaria", iso: "BG", dial: "359" },
  { name: "Canada", iso: "CA", dial: "1" },
  { name: "Chile", iso: "CL", dial: "56" },
  { name: "China", iso: "CN", dial: "86" },
  { name: "Colombia", iso: "CO", dial: "57" },
  { name: "Croatia", iso: "HR", dial: "385" },
  { name: "Cyprus", iso: "CY", dial: "357" },
  { name: "Czech Republic", iso: "CZ", dial: "420" },
  { name: "Denmark", iso: "DK", dial: "45" },
  { name: "Egypt", iso: "EG", dial: "20" },
  { name: "Estonia", iso: "EE", dial: "372" },
  { name: "Finland", iso: "FI", dial: "358" },
  { name: "France", iso: "FR", dial: "33" },
  { name: "Georgia", iso: "GE", dial: "995" },
  { name: "Germany", iso: "DE", dial: "49" },
  { name: "Ghana", iso: "GH", dial: "233" },
  { name: "Greece", iso: "GR", dial: "30" },
  { name: "Hong Kong", iso: "HK", dial: "852" },
  { name: "Hungary", iso: "HU", dial: "36" },
  { name: "India", iso: "IN", dial: "91" },
  { name: "Indonesia", iso: "ID", dial: "62" },
  { name: "Iran", iso: "IR", dial: "98" },
  { name: "Iraq", iso: "IQ", dial: "964" },
  { name: "Ireland", iso: "IE", dial: "353" },
  { name: "Italy", iso: "IT", dial: "39" },
  { name: "Japan", iso: "JP", dial: "81" },
  { name: "Jordan", iso: "JO", dial: "962" },
  { name: "Kazakhstan", iso: "KZ", dial: "7" },
  { name: "Kenya", iso: "KE", dial: "254" },
  { name: "Kuwait", iso: "KW", dial: "965" },
  { name: "Latvia", iso: "LV", dial: "371" },
  { name: "Lebanon", iso: "LB", dial: "961" },
  { name: "Lithuania", iso: "LT", dial: "370" },
  { name: "Luxembourg", iso: "LU", dial: "352" },
  { name: "Malaysia", iso: "MY", dial: "60" },
  { name: "Maldives", iso: "MV", dial: "960" },
  { name: "Mexico", iso: "MX", dial: "52" },
  { name: "Morocco", iso: "MA", dial: "212" },
  { name: "Netherlands", iso: "NL", dial: "31" },
  { name: "New Zealand", iso: "NZ", dial: "64" },
  { name: "Nigeria", iso: "NG", dial: "234" },
  { name: "Norway", iso: "NO", dial: "47" },
  { name: "Oman", iso: "OM", dial: "968" },
  { name: "Pakistan", iso: "PK", dial: "92" },
  { name: "Palestine", iso: "PS", dial: "970" },
  { name: "Philippines", iso: "PH", dial: "63" },
  { name: "Poland", iso: "PL", dial: "48" },
  { name: "Portugal", iso: "PT", dial: "351" },
  { name: "Qatar", iso: "QA", dial: "974" },
  { name: "Romania", iso: "RO", dial: "40" },
  { name: "Russia", iso: "RU", dial: "7" },
  { name: "Saudi Arabia", iso: "SA", dial: "966" },
  { name: "Singapore", iso: "SG", dial: "65" },
  { name: "Slovakia", iso: "SK", dial: "421" },
  { name: "Slovenia", iso: "SI", dial: "386" },
  { name: "South Africa", iso: "ZA", dial: "27" },
  { name: "South Korea", iso: "KR", dial: "82" },
  { name: "Spain", iso: "ES", dial: "34" },
  { name: "Sri Lanka", iso: "LK", dial: "94" },
  { name: "Sweden", iso: "SE", dial: "46" },
  { name: "Switzerland", iso: "CH", dial: "41" },
  { name: "Syria", iso: "SY", dial: "963" },
  { name: "Taiwan", iso: "TW", dial: "886" },
  { name: "Thailand", iso: "TH", dial: "66" },
  { name: "Turkey", iso: "TR", dial: "90" },
  { name: "Ukraine", iso: "UA", dial: "380" },
  { name: "United Arab Emirates", iso: "AE", dial: "971" },
  { name: "United Kingdom", iso: "GB", dial: "44" },
  { name: "United States", iso: "US", dial: "1" },
  { name: "Uzbekistan", iso: "UZ", dial: "998" },
  { name: "Vietnam", iso: "VN", dial: "84" },
  { name: "Yemen", iso: "YE", dial: "967" },
]
